name: Deploy Jekyll Site to GitHub Pages

on:
  push:
    branches:
      - main  # Jalankan workflow ini saat ada perubahan di branch "main"
  pull_request:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Langkah 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Langkah 2: Set up Ruby environment
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0' # Ganti dengan versi Ruby yang kamu butuhkan
          bundler-cache: true  # Meng-cache dependencies untuk mempercepat build

      # Langkah 3: Install Jekyll dan dependensi lainnya
      - name: Install Dependencies
        run: |
          gem install jekyll bundler # Pastikan Jekyll dan bundler terinstal
          bundle install # Install gems sesuai Gemfile

      # Langkah 4: Build Jekyll Site
      - name: Build Jekyll Site
        run: |
          bundle exec jekyll build # Bangun situs Jekyll
          echo "Jekyll site built successfully!"

      # Langkah 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site # Folder output dari Jekyll build
          publish_branch: gh-pages # Branch untuk GitHub Pages
          publish_dir: ./_site # Direktori output yang akan dipublikasikan

      # Langkah 6: Informasi sukses
      - name: Notify Deployment Success
        run: |
          echo "Deployment to GitHub Pages successful!"
